source 'https://supermarket.chef.io'

cookbook 'datadog', '~>2.18.0', git: "https://github.com/datadog/chef-datadog.git"
cookbook 'apt', '~> 7.1.1'
cookbook 'yum', '~> 5.1.0'
cookbook 'windows', '~> 6.0.0'
cookbook 'dd-agent-install', path: './site-cookbooks/dd-agent-install'
cookbook 'dd-agent-upgrade', path: './site-cookbooks/dd-agent-upgrade'
cookbook 'dd-agent-install-script', path: './site-cookbooks/dd-agent-install-script'
cookbook 'dd-agent-step-by-step', path: './site-cookbooks/dd-agent-step-by-step'
cookbook 'dd-agent-import-conf', path: './site-cookbooks/dd-agent-import-conf'
cookbook 'dd-agent-5', path: './site-cookbooks/dd-agent-5'
